In [1]:
import pandas as pd
import lightgbm as lgb
import numpy as np
import pickle
import os

In [2]:
lgb.__version__

'3.0.0'

In [3]:
np.set_printoptions(precision=2)

In [4]:
# Create X_train, y_train, X_test, y_test

X_train = pd.read_feather("X_train.feather")
y_train = pd.read_feather("y_train.feather")

X_test = pd.read_feather("X_test.feather")

print(X_train.shape)
print(y_train.shape)

print(X_test.shape)


(354659, 100)
(354659, 1)
(399950, 100)


In [5]:
param = {}
param['boosting_type']      = 'gbdt'
param['feature_fraction_bynode']   = 0.5
param['objective']          = 'regression'
param['verbosity']          = -1
param['seed'] = 1
param["force_col_wise"] = True
param["boost_from_average"] = False

preds = []
for i in range(5):
    dTrain = lgb.Dataset(X_train, label=y_train)    
    model = lgb.train( param, dTrain, 1000)
    preds.append( model.predict(X_test))
print(np.corrcoef(preds))

[[1.   0.74 0.78 0.87 0.74]
 [0.74 1.   0.74 0.73 0.81]
 [0.78 0.74 1.   0.77 0.73]
 [0.87 0.73 0.77 1.   0.73]
 [0.74 0.81 0.73 0.73 1.  ]]


In [6]:
os.cpu_count()

32

In [7]:
param = {}
param['boosting_type']      = 'gbdt'
param['feature_fraction_bynode']   = 0.5
param['objective']          = 'regression'
param['verbosity']          = -1
param['seed'] = 1
param["force_col_wise"] = True

for n in range(6):
    param["num_threads"] = 2 ** n
    print(f'num threads: {param["num_threads"]}')
    preds = []
    for i in range(5):
        dTrain = lgb.Dataset(X_train, label=y_train)    
        model = lgb.train( param, dTrain, 1000)
        preds.append( model.predict(X_test))
    print(np.corrcoef(preds))

num threads: 1
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
num threads: 2
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
num threads: 4
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
num threads: 8
[[1.   0.89 1.   0.89 0.89]
 [0.89 1.   0.89 1.   1.  ]
 [1.   0.89 1.   0.89 0.89]
 [0.89 1.   0.89 1.   1.  ]
 [0.89 1.   0.89 1.   1.  ]]
num threads: 16
[[1.   0.89 0.83 0.83 0.84]
 [0.89 1.   0.83 0.83 0.83]
 [0.83 0.83 1.   1.   0.85]
 [0.83 0.83 1.   1.   0.85]
 [0.84 0.83 0.85 0.85 1.  ]]
num threads: 32
[[1.   0.83 1.   0.89 0.89]
 [0.83 1.   0.83 0.83 0.83]
 [1.   0.83 1.   0.89 0.89]
 [0.89 0.83 0.89 1.   1.  ]
 [0.89 0.83 0.89 1.   1.  ]]
