In [1]:
import pandas as pd
import lightgbm as lgb
import numpy as np
import pickle

In [2]:
lgb.__version__

'3.0.0'

In [3]:
# Create X_train, y_train, X_test, y_test

X_train = pd.read_feather("X_train.feather")
y_train = pd.read_feather("y_train.feather")

X_test = pd.read_feather("X_test.feather")

print(X_train.shape)
print(y_train.shape)

print(X_test.shape)


(354659, 100)
(354659, 1)
(399950, 100)


In [4]:
param = {}
param['boosting_type']      = 'gbdt'
param['feature_fraction_bynode']   = 0.5
param['objective']          = 'regression'
param['verbosity']          = -1
param['seed'] = 1
param["force_col_wise"] = True

In [5]:
dTrain = lgb.Dataset(X_train, label=y_train) 
model = lgb.train( param, dTrain, 1000)
preds = model.predict(X_test)
preds

array([14.99371066, 14.32515165, 14.59955036, ..., 14.05986162,
       14.49263696, 14.40314711])

In [6]:
dTrain = lgb.Dataset(X_train, label=y_train)    
model2 = lgb.train( param, dTrain, 1000)
preds2 = model2.predict(X_test)
preds2

array([14.70420208, 14.44624769, 14.63780879, ..., 14.65557806,
       15.27629841, 14.79568608])

In [7]:
dTrain = lgb.Dataset(X_train, label=y_train)    
model3 = lgb.train( param, dTrain, 1000)
preds3 = model3.predict(X_test)
preds3

array([14.70420208, 14.44624769, 14.63780879, ..., 14.65557806,
       15.27629841, 14.79568608])

In [8]:
dTrain = lgb.Dataset(X_train, label=y_train)    
model4 = lgb.train( param, dTrain, 1000)
preds4 = model4.predict(X_test)
preds4

array([14.35029278, 14.12778964, 14.39412181, ..., 15.38202428,
       15.76135873, 15.31424203])

In [9]:
model5 = lgb.train( param, dTrain, 1000)
preds5 = model5.predict(X_test)
preds5

array([14.70916412, 14.12738524, 14.40052407, ..., 14.43465334,
       14.59869459, 14.50421264])

In [10]:
np.corrcoef(preds, preds2)

array([[1.        , 0.84808025],
       [0.84808025, 1.        ]])

In [11]:
np.corrcoef(preds, preds3)

array([[1.        , 0.84808138],
       [0.84808138, 1.        ]])