In [1]:
import pandas as pd
import lightgbm as lgb
import numpy as np

In [2]:
lgb.__version__

'3.0.0'

In [3]:
# Create X_train, y_train, X_test, y_test

X_train = pd.read_feather("X_train.feather")
y_train = pd.read_feather("y_train.feather")

X_test = pd.read_feather("X_test.feather")

print(X_train.shape)
print(y_train.shape)

print(X_test.shape)


(354659, 100)
(354659, 1)
(399950, 100)


In [4]:
param = {}
param['boosting_type']      = 'gbdt'
param['feature_fraction']   = 0.2
param['feature_fraction_bynode']   = 0.5 #solves
param['lambda_l2']          = 1
param['learning_rate']      = 0.02
param['max_bin']          = 31
param['max_delta_step']          = 63
param['max_depth']          = 20
param['metric']             = 'rmse'
param['min_data_in_bin']       = 100
param['min_data_in_leaf']   = 8191
param['min_gain_to_split']       = 1
param['num_leaves']         = 100
param['objective']          = 'regression'
param['verbosity']          = -1
param['seed'] = 1
param["force_col_wise"] = True

In [5]:
dTrain = lgb.Dataset(X_train, label=y_train) 
model = lgb.train( param, dTrain, 1000)
preds = model.predict(X_test)
preds

array([15.08536502, 15.08572799, 15.10708202, ..., 15.06541335,
       15.00730375, 14.91226183])

In [6]:
dTrain = lgb.Dataset(X_train, label=y_train)    
model2 = lgb.train( param, dTrain, 1000)
preds2 = model2.predict(X_test)
preds2

array([15.13448509, 15.10872418, 15.0876318 , ..., 15.05337807,
       15.03716028, 14.89823865])

In [7]:
dTrain = lgb.Dataset(X_train, label=y_train)    
model3 = lgb.train( param, dTrain, 1000)
preds3 = model3.predict(X_test)
preds3

array([15.08536502, 15.08572799, 15.10708202, ..., 15.06541335,
       15.00730375, 14.91226183])

In [8]:
dTrain = lgb.Dataset(X_train, label=y_train)    
model4 = lgb.train( param, dTrain, 1000)
preds4 = model4.predict(X_test)
preds4

array([15.06415298, 15.05877895, 15.06493341, ..., 15.08661083,
       15.0318991 , 14.9445281 ])

In [9]:
model5 = lgb.train( param, dTrain, 1000)
preds5 = model5.predict(X_test)
preds5

array([15.06710662, 15.02269787, 15.04029656, ..., 15.07100491,
       15.02228815, 14.90104465])

In [10]:
np.corrcoef(preds, preds2)

array([[1.        , 0.98241227],
       [0.98241227, 1.        ]])

In [11]:
np.corrcoef(preds, preds3)

array([[1., 1.],
       [1., 1.]])