In [9]:
import pandas as pd
import lightgbm as lgb
import numpy as np
import pickle

In [10]:
lgb.__version__

'3.0.0'

In [11]:
# Create X_train, y_train, X_test, y_test

X_train = pd.read_feather("../X_train.feather")
y_train = pd.read_feather("y_train.feather")

X_test = pd.read_feather("../X_test.feather")

print(X_train.shape)
print(y_train.shape)

print(X_test.shape)


(354659, 100)
(354659, 1)
(399950, 100)


In [29]:
param = {}
param['boosting_type']      = 'gbdt'
#param['feature_fraction_bynode']   = 0.5
param['objective']          = 'regression'
param['verbosity']          = -1
param['feature_fraction_seed'] = 1
param["force_col_wise"] = True

In [30]:
dTrain = lgb.Dataset(X_train, label=y_train) 
model = lgb.train( param, dTrain, 1000)
preds = model.predict(X_test)
preds

array([14.63570672, 14.31799952, 14.60157817, ..., 14.68726359,
       14.48253542, 14.97225771])

In [ ]:
for i in range(100):
    dTrain = lgb.Dataset(X_train, label=y_train)    
    model2 = lgb.train( param, dTrain, 1000)
    preds2 = model2.predict(X_test)
    print(np.corrcoef(preds, preds2))

[[1.         0.99998854]
 [0.99998854 1.        ]]
[[1.         0.99999218]
 [0.99999218 1.        ]]
[[1.        0.9999978]
 [0.9999978 1.       ]]
[[1.         0.99999427]
 [0.99999427 1.        ]]
[[1.         0.99999441]
 [0.99999441 1.        ]]
[[1.         0.99999427]
 [0.99999427 1.        ]]
[[1.         0.99999427]
 [0.99999427 1.        ]]
[[1.         0.99999218]
 [0.99999218 1.        ]]
[[1.         0.99999427]
 [0.99999427 1.        ]]
[[1.         0.99999441]
 [0.99999441 1.        ]]
[[1.         0.99999441]
 [0.99999441 1.        ]]
[[1.         0.99999429]
 [0.99999429 1.        ]]
[[1.        0.9999978]
 [0.9999978 1.       ]]
[[1.        0.9999978]
 [0.9999978 1.       ]]
[[1.         0.99999427]
 [0.99999427 1.        ]]
[[1.         0.99999429]
 [0.99999429 1.        ]]
[[1.        0.9999978]
 [0.9999978 1.       ]]
[[1.         0.99999218]
 [0.99999218 1.        ]]
[[1.         0.99999218]
 [0.99999218 1.        ]]
[[1.         0.99998614]
 [0.99998614 1.       

In [31]:
dTrain = lgb.Dataset(X_train, label=y_train)    
model2 = lgb.train( param, dTrain, 1000)
preds2 = model2.predict(X_test)
preds2

array([14.63570672, 14.31799952, 14.60157817, ..., 14.68726359,
       14.48253542, 14.97225771])

In [32]:
dTrain = lgb.Dataset(X_train, label=y_train)    
model3 = lgb.train( param, dTrain, 1000)
preds3 = model3.predict(X_test)
preds3

array([14.63570672, 14.31799952, 14.60157817, ..., 14.68726359,
       14.48253542, 14.97225771])

In [33]:
dTrain = lgb.Dataset(X_train, label=y_train)    
model4 = lgb.train( param, dTrain, 1000)
preds4 = model4.predict(X_test)
preds4

array([14.63570672, 14.31799952, 14.60157817, ..., 14.68726359,
       14.48253542, 14.97225771])

In [34]:
model5 = lgb.train( param, dTrain, 1000)
preds5 = model5.predict(X_test)
preds5

array([14.63570672, 14.31799952, 14.60157817, ..., 14.68726359,
       14.48253542, 14.97225771])

In [35]:
np.corrcoef(preds, preds2)

array([[1.        , 0.99998614],
       [0.99998614, 1.        ]])

In [36]:
np.corrcoef(preds, preds3)

array([[1.        , 0.99999218],
       [0.99999218, 1.        ]])

In [18]:
model.feature_fraction_seed

AttributeError: 'Booster' object has no attribute 'feature_fraction_seed'

In [28]:
model.params

{'boosting_type': 'gbdt',
 'feature_fraction_bynode': 0.5,
 'objective': 'regression',
 'verbosity': -1,
 'feature_fraction_seed': 1,
 'force_col_wise': True,
 'num_iterations': 1000,
 'early_stopping_round': None}

In [21]:
model.attr("feature_fraction_seed")